<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="project" name="pytest" skipped="0" tests="1" time="1.246" timestamp="2021-08-15T18:23:15.434694"><testcase classname="" name="service_1.app.test.test_1" time="0.000"><error message="collection failure">/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:994: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:941: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:219: in _call_with_frames_removed
    ???
&lt;frozen importlib._bootstrap&gt;:994: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:941: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:219: in _call_with_frames_removed
    ???
&lt;frozen importlib._bootstrap&gt;:994: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:971: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:955: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:665: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:678: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:219: in _call_with_frames_removed
    ???
service_1/app/__init__.py:13: in &lt;module&gt;
    from app import routes
service_1/app/routes.py:2: in &lt;module&gt;
    from app.models import Characters
service_1/app/models.py:9: in &lt;module&gt;
    db.create_all()
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:1094: in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:1086: in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:1017: in get_engine
    return connector.get_engine()
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:593: in get_engine
    sa_url, options = self.get_options(sa_url, echo)
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:608: in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:933: in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
E   AttributeError: 'NoneType' object has no attribute 'drivername'</error></testcase></testsuite></testsuites>